# Generated by Django 5.2.1 on 2026-07-01 03:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pricing_unit', models.CharField(choices=[('per_booking', 'Per booking'), ('per_night', 'Per night'), ('per_unit', 'Per unit')], default='per_booking', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='MMK', max_length=3)),
                ('configuration_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=24, unique=True)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('core_customer_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='pending_payment', max_length=32)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=64)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('guest_market', models.CharField(choices=[('all', 'All'), ('local', 'Local'), ('foreign', 'Foreign')], default='local', max_length=16)),
                ('currency', models.CharField(default='MMK', max_length=3)),
                ('room_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('add_on_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cancellation_policy_snapshot', models.JSONField(blank=True, default=dict)),
                ('special_request', models.TextField(blank=True)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_business_id', models.PositiveBigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('cover_image_url', models.URLField(blank=True, max_length=1000)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('core_snapshot', models.JSONField(blank=True, default=dict)),
                ('core_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('guest_market', models.CharField(choices=[('all', 'All'), ('local', 'Local'), ('foreign', 'Foreign')], default='all', max_length=16)),
                ('currency', models.CharField(default='MMK', max_length=3)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('breakfast_included', models.BooleanField(default=False)),
                ('refundable', models.BooleanField(default=True)),
                ('cancellation_policy', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('add_on_snapshot', models.JSONField(default=dict)),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_add_ons', to='booking.addon')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('extra_beds', models.PositiveSmallIntegerField(default=0)),
                ('room_type_snapshot', models.JSONField(default=dict)),
                ('rate_plan_snapshot', models.JSONField(default=dict)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='booking.booking')),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_rooms', to='booking.rateplan')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('nrc_number', models.CharField(blank=True, max_length=100)),
                ('passport_number', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='booking.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.hotel'),
        ),
        migrations.AddField(
            model_name='addon',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='booking.hotel'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially refunded')], default='pending', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(max_length=3)),
                ('invoice_number', models.CharField(max_length=32, unique=True)),
                ('receipt_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='booking.booking')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_physical_room_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('room_number', models.CharField(max_length=50)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('building', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('cleaning', 'Cleaning'), ('out_of_service', 'Out of service')], default='vacant', max_length=32)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_rooms', to='booking.hotel')),
            ],
            options={
                'ordering': ['building', 'floor', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='DailyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('min_stay', models.PositiveSmallIntegerField(default=1)),
                ('closed_to_arrival', models.BooleanField(default=False)),
                ('closed_to_departure', models.BooleanField(default=False)),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rates', to='booking.rateplan')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('booking_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='booking.bookingroom')),
                ('physical_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='booking.physicalroom')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_room_type_id', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=1000)),
                ('max_adults', models.PositiveSmallIntegerField(default=1)),
                ('max_children', models.PositiveSmallIntegerField(default=0)),
                ('max_occupancy', models.PositiveSmallIntegerField(default=1)),
                ('default_inventory', models.PositiveSmallIntegerField(default=0)),
                ('booking_enabled', models.BooleanField(default=True)),
                ('core_active', models.BooleanField(default=True)),
                ('core_snapshot', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='booking.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='rateplan',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_plans', to='booking.roomtype'),
        ),
        migrations.AddField(
            model_name='physicalroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_rooms', to='booking.roomtype'),
        ),
        migrations.CreateModel(
            name='DailyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_date', models.DateField()),
                ('total_rooms', models.PositiveSmallIntegerField()),
                ('held_rooms', models.PositiveSmallIntegerField(default=0)),
                ('reserved_rooms', models.PositiveSmallIntegerField(default=0)),
                ('stop_sell', models.BooleanField(default=False)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_inventory', to='booking.roomtype')),
            ],
            options={
                'ordering': ['stay_date'],
            },
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_rooms', to='booking.roomtype'),
        ),
        migrations.CreateModel(
            name='BookingRoomNight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_date', models.DateField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('booking_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nights', to='booking.bookingroom')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('booking_room', 'stay_date'), name='uniq_booking_room_night')],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['hotel', 'check_in', 'check_out'], name='booking_boo_hotel_i_ff8c07_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['reference'], name='booking_boo_referen_3aa8ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('hotel', 'idempotency_key'), name='uniq_booking_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='addon',
            constraint=models.UniqueConstraint(fields=('hotel', 'code'), name='uniq_add_on_code'),
        ),
        migrations.AddConstraint(
            model_name='dailyrate',
            constraint=models.UniqueConstraint(fields=('rate_plan', 'stay_date'), name='uniq_daily_rate'),
        ),
        migrations.AddConstraint(
            model_name='roomtype',
            constraint=models.UniqueConstraint(fields=('hotel', 'core_room_type_id'), name='uniq_core_room_type_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='rateplan',
            constraint=models.UniqueConstraint(fields=('room_type', 'code'), name='uniq_rate_plan_code'),
        ),
        migrations.AddConstraint(
            model_name='physicalroom',
            constraint=models.UniqueConstraint(fields=('hotel', 'room_number'), name='uniq_room_number_per_hotel'),
        ),
        migrations.AddIndex(
            model_name='dailyinventory',
            index=models.Index(fields=['room_type', 'stay_date'], name='booking_dai_room_ty_5311e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyinventory',
            constraint=models.UniqueConstraint(fields=('room_type', 'stay_date'), name='uniq_inventory_day'),
        ),
    ]
