# Generated by Django 5.2.1 on 2026-07-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroomnight',
            name='extra_bed_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='extra_bed_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
