# Generated by Django 5.2.1 on 2026-07-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingroomnight_extra_bed_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreIntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('core_business_id', models.PositiveBigIntegerField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='access_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='core_rate_plan_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
