# Generated by Django 5.2.1 on 2026-07-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_coreintegrationevent_hotel_access_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('demo', 'Demo'), ('cash', 'Cash'), ('mmqr', 'MMQR'), ('other', 'Other')], max_length=50),
        ),
    ]
