# Generated by Django 5.2.1 on 2026-07-01 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_payment_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null means no end date.', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('min_stay', models.PositiveSmallIntegerField(default=1)),
                ('closed_to_arrival', models.BooleanField(default=False)),
                ('closed_to_departure', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_periods', to='booking.rateplan')),
            ],
            options={
                'ordering': ['start_date', 'id'],
                'indexes': [models.Index(fields=['rate_plan', 'start_date', 'end_date'], name='booking_rat_rate_pl_19c100_idx')],
            },
        ),
    ]
