# Generated by Django 5.2.1 on 2026-07-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_hotel_package_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroom',
            name='option_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='preference_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bookingroomnight',
            name='option_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='physicalroom',
            name='core_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
