# Generated by Django 5.2.1 on 2026-07-24 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_physicalroom_core_building_floor_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_meal_plan_id', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('included_meals', models.JSONField(blank=True, default=list)),
                ('availability', models.CharField(choices=[('guest_only', 'Guest Only'), ('public', 'Public / Walk-in')], default='guest_only', max_length=32)),
                ('local_base_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('local_usd_display_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('foreign_base_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('foreign_usd_display_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('core_active', models.BooleanField(default=True)),
                ('core_snapshot', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='booking.hotel')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoomTypeMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_included', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('is_guest_selectable', models.BooleanField(default=True)),
                ('use_hotel_default_price', models.BooleanField(default=True)),
                ('local_base_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('local_usd_display_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('foreign_base_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('foreign_usd_display_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('core_snapshot', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_type_links', to='booking.mealplan')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_links', to='booking.roomtype')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='mealplan',
            constraint=models.UniqueConstraint(fields=('hotel', 'core_meal_plan_id'), name='uniq_core_meal_plan_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='roomtypemealplan',
            constraint=models.UniqueConstraint(fields=('room_type', 'meal_plan'), name='uniq_booking_room_type_meal_plan'),
        ),
    ]
