# Generated by Django 5.2.1 on 2026-07-24 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_meal_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroom',
            name='meal_plan_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_rooms', to='booking.roomtypemealplan'),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='meal_plan_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='meal_plan_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='bookingroomnight',
            name='meal_plan_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
