# Generated by Django 5.2.1 on 2026-07-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_bookingroom_meal_plan_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='meal_windows',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
