# Generated by Codex on 2026-07-27

from django.db import migrations, models


def backfill_pricing_mode(apps, schema_editor):
    RoomTypeMealPlan = apps.get_model("booking", "RoomTypeMealPlan")
    RoomTypeMealPlan.objects.filter(is_included=True).update(pricing_mode="included_in_room_price")
    RoomTypeMealPlan.objects.filter(is_included=False, use_hotel_default_price=True).update(pricing_mode="hotel_default")
    RoomTypeMealPlan.objects.filter(is_included=False, use_hotel_default_price=False).update(pricing_mode="custom")


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0017_mealplan_meal_windows"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtypemealplan",
            name="pricing_mode",
            field=models.CharField(
                choices=[
                    ("hotel_default", "Use Hotel Default Meal Price"),
                    ("custom", "Use Custom Room Type Meal Price"),
                    ("included_in_room_price", "Included In Room Price"),
                ],
                default="hotel_default",
                max_length=32,
            ),
        ),
        migrations.RunPython(backfill_pricing_mode, migrations.RunPython.noop),
    ]
