# Generated by Codex on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0018_roomtypemealplan_pricing_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("demo", "Demo"),
                    ("aya", "AYA"),
                    ("cash", "Cash"),
                    ("mmqr", "MMQR"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
