# Generated by Django 5.2.1 on 2026-08-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_guest_identity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingroom',
            name='breakfast_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='breakfast_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='bookingroomnight',
            name='breakfast_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='is_default_for_room_type_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='breakfast_custom_foreign_base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='breakfast_custom_foreign_usd_display_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='breakfast_custom_local_base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='breakfast_custom_local_usd_display_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='breakfast_plan_type',
            field=models.CharField(choices=[('no_breakfast', 'No Breakfast'), ('included_in_room_price', 'Breakfast Included In Room Price'), ('hotel_default_price', 'Use Hotel Default Breakfast Price'), ('custom_price', 'Use Custom Breakfast Price')], default='no_breakfast', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='mealplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_for_room_type_breakfast', True)), fields=('hotel',), name='uniq_booking_default_breakfast_per_hotel'),
        ),
    ]
