# Generated by Django 5.2.1 on 2026-08-10 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_bookingroom_breakfast_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_verification_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checked_in_by_core_user_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('ota', 'OTA'), ('direct', 'Direct Booking'), ('phone', 'Phone / On-call'), ('walk_in', 'Walk-in'), ('pms', 'PMS')], default='direct', max_length=24),
        ),
        migrations.AddField(
            model_name='booking',
            name='source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='GuestIdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('nrc_front', 'NRC Front'), ('nrc_back', 'NRC Back'), ('passport', 'Passport'), ('visa', 'Visa'), ('other', 'Other')], max_length=24)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='booking/guest-identities/%Y/%m/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by_core_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to='booking.guest')),
            ],
            options={
                'ordering': ['document_type', 'id'],
                'constraints': [models.UniqueConstraint(fields=('guest', 'document_type'), name='uniq_guest_identity_document_type')],
            },
        ),
    ]
