# Generated by Django 5.2.1 on 2026-08-18 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_alter_guestidentitydocument_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalRoomActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reserved', 'Reserved'), ('room_assigned', 'Room assigned'), ('room_unassigned', 'Room unassigned'), ('room_changed', 'Room changed'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out'), ('cleaning_started', 'Cleaning started'), ('cleaning_completed', 'Cleaning completed'), ('status_changed', 'Status changed'), ('out_of_service_started', 'Out of service started'), ('out_of_service_ended', 'Out of service ended'), ('block_created', 'Block created'), ('block_updated', 'Block updated'), ('unblocked', 'Unblocked')], max_length=40)),
                ('actor_type', models.CharField(choices=[('hotel_admin', 'Hotel admin'), ('guest', 'Guest'), ('ota', 'OTA'), ('system', 'System')], default='system', max_length=24)),
                ('actor_core_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('old_status', models.CharField(blank=True, max_length=32)),
                ('new_status', models.CharField(blank=True, max_length=32)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_history', to='booking.physicalroomblock')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_room_history', to='booking.booking')),
                ('physical_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_history', to='booking.physicalroom')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['physical_room', 'created_at'], name='booking_room_hist_date_idx'), models.Index(fields=['physical_room', 'action'], name='booking_room_hist_action_idx')],
            },
        ),
    ]
