# Generated by Django 5.2.1 on 2026-08-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_alter_physicalroomactionhistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='components',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='package_pricing_mode',
            field=models.CharField(default='sum_default_prices', max_length=32),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='plan_type',
            field=models.CharField(default='single', max_length=16),
        ),
    ]
