# Generated by Django 5.2.1 on 2026-09-23 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0053_separate_ota_pms_invoice_charge_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinventory',
            name='closed_rooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OTAInventoryClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('close_all', models.BooleanField(default=False)),
                ('rooms_to_close', models.PositiveSmallIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_by_core_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_inventory_closures', to='booking.roomtype')),
            ],
            options={
                'ordering': ['start_date', 'end_date', 'id'],
                'indexes': [models.Index(fields=['room_type', 'start_date', 'end_date'], name='booking_ota_close_dates_idx')],
            },
        ),
    ]
