# Generated by Django 5.2.1 on 2026-09-24 01:57

import django.db.models.functions.text
from django.db import migrations, models


def normalize_unique_charge_names(apps, schema_editor):
    Hotel = apps.get_model("booking", "Hotel")
    for model_name, config_field in (
        ("OTAInvoiceCharge", "ota_invoice_charges"),
        ("PMSInvoiceCharge", "pms_invoice_charges"),
    ):
        Charge = apps.get_model("booking", model_name)
        seen = set()
        for charge in Charge.objects.order_by("hotel_id", "id").iterator():
            title = (charge.title or "").strip()
            key = (charge.hotel_id, title.casefold())
            if not title or key in seen:
                charge.delete()
                continue
            seen.add(key)
            if charge.title != title:
                charge.title = title
                charge.save(update_fields=["title"])

        for hotel in Hotel.objects.all().iterator():
            config = {"taxes": [], "service_charges": []}
            for charge in Charge.objects.filter(hotel_id=hotel.id).order_by(
                "charge_type", "sort_order", "id",
            ):
                category = "taxes" if charge.charge_type == "tax" else "service_charges"
                config[category].append({
                    "title": charge.title,
                    "mode": charge.mode,
                    "value": str(charge.value),
                })
            setattr(hotel, config_field, config)
            hotel.save(update_fields=[config_field])


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0054_dailyinventory_closed_rooms_otainventoryclosure'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='otainvoicecharge',
            name='uniq_ota_invoice_charge_title',
        ),
        migrations.RemoveConstraint(
            model_name='pmsinvoicecharge',
            name='uniq_pms_invoice_charge_title',
        ),
        migrations.RunPython(normalize_unique_charge_names, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='otainvoicecharge',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('hotel'), name='uniq_ota_invoice_charge_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='pmsinvoicecharge',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('hotel'), name='uniq_pms_invoice_charge_name_ci'),
        ),
    ]
